### ISSUE TITLE
LightningCSS instead of CSSO (or an option)

### ISSUE THREAD

**Issue by kurtextrem** [PlayForm/Compress#146]
Hi, thank you for making this first of all!

There is LightningCSS from the author of Parcel: https://lightningcss.dev/, which seems to better and faster than CSSO. So maybe switching to it, or adding an option would make sense. What do you think?

**Comment by NikolaRHristov** [comment]
It's been on my backlog for a couple of months now, but `CSSO` offers structural optimizations as well as minification and that's why I haven't implemented it yet.

**Comment by NikolaRHristov** [comment]
@kurtextrem Fixed in the latest `astro-compress` [v2.2.24](https://github.com/PlayForm/Compress/releases/tag/AstroCompress%2Fv2.2.24) and `@playform/compress` [v0.0.6](https://github.com/PlayForm/Compress/releases/tag/Compress%2Fv0.0.6) Can you give it a go ?

**Comment by kurtextrem** [comment]
Pretty dope, thank you!
