### ISSUE TITLE
LightningCSS compression not working

### ISSUE THREAD

**Issue by J05HI** [PlayForm/Compress#237]
The shorthand compression of LightningCSS is not working: [https://lightningcss.dev/minification.html#shorthands](https://lightningcss.dev/minification.html#shorthands)

`
.myclass {
        border-width:0;
        border-style:solid;
        border-color:#e5e7eb;
}
`
gets compressed to
`
.myclass{border-width:0;border-style:solid;border-color:#e5e7eb}
`
It should instead be compressed to
`
.myclass{border:0 solid #e5e7eb}
`

**Comment by NikolaRHristov** [comment]
It's not released yet, expect in the next version `v2.3.0`.

**Comment by NikolaRHristov** [comment]
@J05HI Fixed in the latest `astro-compress` [v2.2.24](https://github.com/PlayForm/Compress/releases/tag/AstroCompress%2Fv2.2.24) and `@playform/compress` [v0.0.6](https://github.com/PlayForm/Compress/releases/tag/Compress%2Fv0.0.6) Can you give it a go ?
