### ISSUE TITLE
HTML minifier too aggressive with whitespaces

### ISSUE THREAD

**Issue by gw2princeps** [PlayForm/Compress#84]
Hey, 

so it appears like this minifier removes all kinds of whitespaces, even those in front of an astro component. 

![image](https://user-images.githubusercontent.com/21026467/221567702-a856b175-91f0-45b1-b10d-de692bd9e17a.png)
Compared to what it looks like with `html: false`. 
![image](https://user-images.githubusercontent.com/21026467/221567761-0d8a8c8b-54ab-4d50-a078-9c6f5274f146.png)

I think it is sensible to preserve these whitespaces.

**Comment by nikolaxhristov** [comment]
Without `collapseWhitespace: true` the website doesn't get minified at all. You can put an `&nbsp;` before the web component or style it with CSS. An alternative for you would be to disable the whitespace minification by setting:

```ts
// @ts-nocheck
import { defineConfig } from "astro/config";

import compress from "astro-compress";
export default defineConfig({
	integrations: [
		compress({
			html: {
				collapseWhitespace: false,
			},
		}),
	],
});
```
