### ISSUE TITLE
Use minify-html

### ISSUE THREAD

**Issue by fabriziogiordano** [PlayForm/Compress#94]
_This is not an issue but a feature request._

I manage a site in astro that builds about 65,000 html files.
I used astro-compress for a while and the compression phase time alone was about 45 minutes on a small server.

I recently switched to https://github.com/wilsonzlin/minify-html and now the compression time is 3 minutes, 1.5 orders of magnitude less time. Pretty incredible.

Is it possible to explore the opportunity to use this compress instead of html-minify-terser currently used?

**Comment by nikolaxhristov** [comment]
Hi, I have tested it before, but got about the same build times. You can try it out at https://github.com/astro-community/astro-compress/tree/minify-html to see if you have better results. If you have used the rust library that's why you probably noticed the smaller build times.

**Comment by nikolaxhristov** [comment]
Yeah the rust minification is cool, there aren't many libraries that support HTML minification, but the npm package uses a binding which is slower than the cli.
